window.PROPERTIES = [
  {id:"takadanobaba-1-2f",name:"高田馬場1丁目・店舗（2階）",station:"高田馬場",walk:3,address:"東京都新宿区高田馬場1丁目",type:"貸店舗・居抜き",area:72.23,floor:"2階",rent:"44万円 / 月",structure:"公開情報なし",elevator:"不明",exits:"不明",published:"登録日 2026-09-18",fit:"review",fitLabel:"要重点確認",reason:"面積は基準を満たすが2階。保育用途の可否、2方向避難、階段幅、消防設備を優先確認。現テナントはポーカーバー。",source:"https://www.inshokuten.com/bukken/kanto/bukkens/list/?form%5Bsearch_line%5D%5B%5D=2&form%5Bsearch_station%5D%5B%5D=241&form%5Bsearch_walk_minutes%5D=4",sourceName:"飲食店ドットコム",evidence:"駅徒歩3分、21.85坪。重飲食を含む業種相談可として掲載。"},
  {id:"takadanobaba-3-1f",name:"高田馬場3丁目・路面店舗（1階）",station:"高田馬場",walk:3,address:"東京都新宿区高田馬場3丁目",type:"貸店舗・スケルトン",area:66.91,floor:"1階",rent:"99万円 / 月",structure:"公開情報なし",elevator:"不明",exits:"不明",published:"登録日 2026-09-15",fit:"promising",fitLabel:"優先確認候補",reason:"1階路面かつ60㎡超で避難面の検討を進めやすい。賃料は高いが、保育用途・採光・換気・第二出口を確認する価値がある。",source:"https://www.inshokuten.com/bukken/kanto/bukkens/list/?form%5Bsearch_line%5D%5B%5D=2&form%5Bsearch_station%5D%5B%5D=241&form%5Bsearch_walk_minutes%5D=4",sourceName:"飲食店ドットコム",evidence:"さかえ通り沿い、20.24坪、飲食可の路面物件として掲載。"},
  {id:"takadanobaba-3-2f",name:"高田馬場3丁目・店舗（2階）",station:"高田馬場",walk:3,address:"東京都新宿区高田馬場3丁目",type:"貸店舗・スケルトン",area:75.40,floor:"2階",rent:"83万円 / 月",structure:"公開情報なし",elevator:"不明",exits:"不明",published:"登録日 2026-09-15",fit:"review",fitLabel:"要重点確認",reason:"面積は十分だが2階のため、独立した避難経路の有無が重要。保育用途、EV、階段、避難バルコニーを図面で確認。",source:"https://www.inshokuten.com/bukken/kanto/bukkens/list/?form%5Bsearch_line%5D%5B%5D=2&form%5Bsearch_station%5D%5B%5D=241&form%5Bsearch_walk_minutes%5D=4",sourceName:"飲食店ドットコム",evidence:"22.81坪、駅徒歩3分。飲食・クリニック・教室等の業種表示あり。"},
  {id:"takadanobaba-1-1f",name:"高田馬場1丁目・路面店舗（1階）",station:"高田馬場",walk:3,address:"東京都新宿区高田馬場1丁目",type:"貸店舗・スケルトン",area:73.52,floor:"1階",rent:"122.32万円 / 月",structure:"公開情報なし",elevator:"不明",exits:"不明",published:"登録日 2026-09-15",fit:"promising",fitLabel:"優先確認候補",reason:"1階・73㎡で初期条件は良好。高額賃料と繁華性を踏まえ、送迎動線、騒音、保育用途、第二出口を確認。",source:"https://www.inshokuten.com/bukken/kanto/bukkens/list/?form%5Bsearch_line%5D%5B%5D=2&form%5Bsearch_station%5D%5B%5D=241&form%5Bsearch_walk_minutes%5D=4",sourceName:"飲食店ドットコム",evidence:"22.24坪、重飲食可の路面物件として掲載。"},
  {id:"nishi-okubo-eleven",name:"西大久保イレブン 101",station:"新大久保",walk:9,address:"東京都新宿区大久保2-14-16",type:"事務所 / SOHO（媒体により用途表記が相違）",area:148.0,floor:"1階",rent:"45.98万円 / 月",structure:"RC・1982年5月",elevator:"不明",exits:"不明",published:"掲載日 2026-06-24、2026-09-21再確認",fit:"promising",fitLabel:"優先確認候補",reason:"1階かつ面積が大きい有力候補。ただし別媒体に事務所不可の記載もあり、所有者の保育用途承諾を最初に確認する必要がある。",source:"https://www.homemate.co.jp/dtl-D664001280101/",sourceName:"ホームメイト",evidence:"同一住所の複数媒体で面積・徒歩時間は概ね一致。賃料と用途条件には差異あり。"},
  {id:"tsuchiya-2f",name:"土屋ビル 2階",station:"新大久保",walk:3,address:"東京都新宿区百人町2-5-4",type:"店舗 / 事務所（クリニック等相談可）",area:195.04,floor:"2階 / 8階建",rent:"86万円＋共益費5万円 / 月（税別）",structure:"SRC・1989年・新耐震",elevator:"不明",exits:"不明",published:"更新日 2026-09-09",fit:"review",fitLabel:"要重点確認",reason:"ワンフロアで面積は十分。2階のため、2方向避難・階段幅・防火区画・EVを図面確認。用途変更の可能性も行政へ要相談。",source:"https://birusaku.jp/lines/search?stations%5B0%5D=%E5%A4%A7%E4%B9%85%E4%BF%9D",sourceName:"ビルサク",evidence:"大久保駅徒歩4分、新大久保駅徒歩3分。2026年11月入居予定。"},
  {id:"tsuchiya-3f",name:"土屋ビル 3階",station:"新大久保",walk:3,address:"東京都新宿区百人町2-5-4",type:"店舗 / 事務所（クリニック等相談可）",area:195.05,floor:"3階 / 8階建",rent:"86万円＋共益費5万円 / 月（税別）",structure:"SRC・1989年・新耐震",elevator:"不明",exits:"不明",published:"更新日 2026-09-09",fit:"review",fitLabel:"要重点確認",reason:"面積は十分だが3階は幼児避難のハードルが上がる。屋外階段を含む2方向避難、排煙、消防設備、EVを最優先で確認。",source:"https://birusaku.jp/lines/search?stations%5B0%5D=%E5%A4%A7%E4%B9%85%E4%BF%9D",sourceName:"ビルサク",evidence:"大久保駅徒歩4分、新大久保駅徒歩3分。2026年11月入居予定。"},
  {id:"kabukicho-2f",name:"歌舞伎町2丁目・店舗（2階）",station:"新宿",walk:3,address:"東京都新宿区歌舞伎町2丁目",type:"貸店舗・居抜き",area:99.17,floor:"2階",rent:"相談",structure:"公開情報なし",elevator:"不明",exits:"不明",published:"登録日 2026-09-19",fit:"review",fitLabel:"要重点確認",reason:"駅近・99㎡だが、前テナントが焼肉店で繁華街立地。保育用途の受入れ、周辺環境、臭気設備撤去、避難経路を慎重に確認。",source:"https://www.inshokuten.com/bukken/kanto/bukkens/list/local-23ward/station-219/walkminutes-1/",sourceName:"飲食店ドットコム",evidence:"新宿駅徒歩3分、30坪。新大久保駅からも徒歩5分として別検索に掲載。"},
  {id:"tk-shintoshin-2f",name:"TK新都心ビル 2階",station:"新宿",walk:3,address:"東京都新宿区西新宿1-23-1",type:"事務所",area:158.04,floor:"2階 / 地上10階・地下2階",rent:"相談",structure:"SRC・RC・1992年11月・新耐震",elevator:"有",exits:"不明",published:"募集確認 2026-07-06、2026-09-21再確認",fit:"review",fitLabel:"要重点確認",reason:"駅近・新耐震・EVありで建物条件は良い。一方、事務所募集のため保育用途への変更可否と2方向避難、給排水工事可否を先に確認。",source:"https://www.officetar.jp/building/2220/",sourceName:"オフィスター",evidence:"2階47.81坪、即日。男女別トイレ・個別空調の記載あり。"},
  {id:"minami-ikebukuro-1f",name:"南池袋2丁目・店舗事務所（1階）",station:"池袋",walk:5,address:"東京都豊島区南池袋2丁目",type:"店舗 / 事務所・スケルトン",area:133.46,floor:"1階 / 地上10階・地下1階",rent:"186.5094万円 / 月",structure:"S造・2014年12月",elevator:"不明",exits:"不明",published:"公開日 2026-07-23、2026-09-21再確認",fit:"promising",fitLabel:"優先確認候補",reason:"1階・新しい建物・133㎡で物理条件は有望。賃料が非常に高く、保育用途、送迎スペース、第二出口、採光を確認して事業性と合わせて判断。",source:"https://mapfan.com/realestate/details/69ba21ba020c0805a5fa1eea",sourceName:"MapFan / アットホーム",evidence:"池袋駅徒歩5分、天井高2700mm、軽飲食可として複数媒体に掲載。"},
  {id:"ikebukuro-first",name:"池袋ファーストビル 3階",station:"池袋",walk:3,address:"東京都豊島区西池袋3-29-11",type:"店舗 / 事務所",area:126.02,floor:"3階 / 地上6階・地下1階",rent:"82.5万円 / 月（税込）",structure:"RC・1980年11月",elevator:"有（1基）",exits:"不明",published:"更新日 2026-08-05、別媒体 2026-08-17",fit:"review",fitLabel:"要重点確認",reason:"駅近・面積合格・EVあり。ただし3階かつ旧耐震期の竣工で、第二出口や避難設備は不明。用途承諾と耐震・消防条件を優先確認。",source:"https://tempoly.jp/property/O-1031432911-3",sourceName:"TEMPOLY",evidence:"別媒体でも同住所・同面積・税別75万円、EV1基を確認。"},
  {id:"homes-takadanobaba-2f",name:"高田馬場・貸事務所（2階）",station:"高田馬場",walk:4,address:"東京都新宿区高田馬場",type:"貸事務所",area:63.14,floor:"2階",rent:"27.5万円 / 月",structure:"S造・1993年10月",elevator:"有",exits:"不明",published:"LIFULL HOME'Sで2026-09-21再確認",fit:"review",fitLabel:"要重点確認",reason:"駅徒歩4分・EVありで利便性は高いが、2階かつ事務所募集。保育用途の承諾、独立した第二出口、階段幅、採光・換気、消防設備を確認。",source:"https://www.homes.co.jp/chintai/b-1457150042363/",sourceName:"LIFULL HOME'S",evidence:"HOME'S物件番号 0145715-0042363。63.14㎡、2階、鉄骨造、エレベーターありとして掲載。"},
  {id:"homes-takadanobaba-1f",name:"高田馬場1丁目・貸事務所（1階）",station:"高田馬場",walk:6,address:"東京都新宿区高田馬場1丁目",type:"貸事務所",area:66.11,floor:"1階",rent:"28.6万円 / 月",structure:"SRC・築44年",elevator:"無",exits:"不明",published:"LIFULL HOME'Sで2026-09-21再確認",fit:"promising",fitLabel:"優先確認候補",reason:"1階・60㎡超で避難計画を検討しやすい。EVなしは1階利用では影響が小さいが、保育用途の承諾、段差、第二出口、採光・換気を確認。",source:"https://www.homes.co.jp/chintai/b-1457150043147/",sourceName:"LIFULL HOME'S",evidence:"西早稲田駅徒歩4分、高田馬場駅徒歩6分。HOME'S物件番号 0145715-0043147。"},
  {id:"homes-carmel-103",name:"カーメルI 103",station:"西新宿",walk:4,address:"東京都新宿区西新宿",type:"貸店舗 / 事務所",area:65.59,floor:"1階 / 8階建",rent:"34.9184万円 / 月",structure:"築37年（構造は要確認）",elevator:"不明",exits:"不明",published:"LIFULL HOME'Sで2026-09-21再確認",fit:"promising",fitLabel:"優先確認候補",reason:"1階・65㎡で初期条件は良好。保育用途の承諾、独立した第二出口、道路からの段差、採光・換気、給排水工事の可否を確認。",source:"https://www.homes.co.jp/chintai/b-1577540000026/",sourceName:"LIFULL HOME'S",evidence:"西新宿駅徒歩4分、新宿駅徒歩13分。1階103号室、65.59㎡として掲載。"}
];
