// 公開募集情報の確認記録。担当者の対応状況・メモとは別管理です。
window.PROPERTIES = [
  {
    "id": "takadanobaba-1-2f",
    "name": "高田馬場1丁目・店舗（2階）",
    "station": "高田馬場",
    "walk": 3,
    "address": "東京都新宿区高田馬場1丁目",
    "type": "貸店舗・居抜き",
    "area": 72.23,
    "floor": "2階",
    "rent": "44万円 / 月",
    "structure": "不明",
    "elevator": "不明",
    "exits": "不明",
    "published": "情報登録 2026-08-19／媒体更新 2026-09-18",
    "fit": "inactive",
    "fitLabel": "過去情報",
    "reason": "募集・掲載終了の記録です。現在の検討候補からは除外し、対応履歴を残しています。掲載終了だけでは成約の有無は判断できません。",
    "source": "https://www.inshokuten.com/bukken/bukkens/399219",
    "sourceName": "飲食店ドットコム",
    "evidence": "72.23㎡・高田馬場駅3分。旧記録の44万円・2階を履歴として保持。",
    "checkedAt": "2026-09-23",
    "listingState": "ended",
    "listingNote": "原掲載に募集終了の表示。階数等の非公開項目は旧記録。",
    "contact": {
      "building": "ビル名：不明",
      "url": "https://www.inshokuten.com/bukken/bukkens/399219",
      "company": "現在の取扱窓口：不明",
      "contact": "募集終了のため、元の掲載ページは履歴確認用です。"
    }
  },
  {
    "id": "takadanobaba-3-1f",
    "name": "高田馬場3丁目・路面店舗（1階）",
    "station": "高田馬場",
    "walk": 3,
    "address": "東京都新宿区高田馬場3丁目",
    "type": "貸店舗・スケルトン",
    "area": 66.91,
    "floor": "1階",
    "rent": "99万円 / 月",
    "structure": "不明",
    "elevator": "不明",
    "exits": "不明",
    "published": "掲載日・媒体更新日：不明（一般公開部分）",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "1階・検索面積条件には該当。間口約1.5mの記載があり、送迎動線・避難幅を重点確認。独立した2出口、保育用途、採光・換気、実際に使える保育面積は不明。",
    "source": "https://www.inshokuten.com/bukken/bukkens/401845",
    "sourceName": "飲食店ドットコム",
    "evidence": "JR高田馬場3分／東西線2分。引渡し2026年11月中旬。1階・2階は別区画として各1件。飲食可は保育用途可を意味しません。",
    "checkedAt": "2026-09-23",
    "listingState": "listed",
    "listingNote": "募集詳細を確認。空室・保育用途の承諾は未確認。"
  },
  {
    "id": "takadanobaba-3-2f",
    "name": "高田馬場3丁目・店舗（2階）",
    "station": "高田馬場",
    "walk": 3,
    "address": "東京都新宿区高田馬場3丁目",
    "type": "貸店舗・スケルトン",
    "area": 75.4,
    "floor": "2階",
    "rent": "83万円 / 月",
    "structure": "不明",
    "elevator": "不明",
    "exits": "不明",
    "published": "掲載日・媒体更新日：不明（一般公開部分）",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "2階・検索面積条件には該当。間口約1.5mの記載があり、送迎動線・避難幅を重点確認。独立した2出口、保育用途、採光・換気、実際に使える保育面積は不明。",
    "source": "https://www.inshokuten.com/bukken/bukkens/401847",
    "sourceName": "飲食店ドットコム",
    "evidence": "JR高田馬場3分／東西線2分。引渡し2026年11月中旬。1階・2階は別区画として各1件。飲食可は保育用途可を意味しません。",
    "checkedAt": "2026-09-23",
    "listingState": "listed",
    "listingNote": "募集詳細を確認。空室・保育用途の承諾は未確認。"
  },
  {
    "id": "takadanobaba-1-1f",
    "name": "高田馬場1丁目・路面店舗（1階）",
    "station": "高田馬場",
    "walk": 3,
    "address": "東京都新宿区高田馬場1丁目",
    "type": "貸店舗・スケルトン",
    "area": 73.52,
    "floor": "1階",
    "rent": "122.32万円 / 月",
    "structure": "不明",
    "elevator": "不明",
    "exits": "不明",
    "published": "掲載日・媒体更新日：不明（旧記録の9月15日は未再検証）",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "今回、原掲載を取得できず募集継続は不明。旧記録は1階73.52㎡ですが、最新条件と保育用途・避難動線を確認してから検討。",
    "source": "https://www.inshokuten.com/bukken/bukkens/393547",
    "sourceName": "飲食店ドットコム",
    "evidence": "22.24坪、重飲食可の路面物件として掲載。",
    "checkedAt": "2026-09-23",
    "listingState": "unverified",
    "listingNote": "原掲載の取得に失敗。募集終了とは断定できません。"
  },
  {
    "id": "nishi-okubo-eleven",
    "name": "西大久保イレブン 101",
    "station": "新大久保",
    "walk": 9,
    "address": "東京都新宿区大久保2-14-16",
    "type": "事務所 / SOHO（媒体により用途表記が相違）",
    "area": 148,
    "floor": "1階",
    "rent": "45.98万円 / 月",
    "structure": "RC・1982年5月",
    "elevator": "不明",
    "exits": "不明",
    "published": "掲載日 2026-06-24（旧記録・未再検証）",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "1階・148㎡は旧記録。事務所利用の可否に媒体間の相違があるため、保育用途を含む所有者承諾と最新の募集継続を先に確認。",
    "source": "https://www.homemate.co.jp/dtl-D664001280101/",
    "sourceName": "ホームメイト",
    "evidence": "同一住所の複数媒体で面積・徒歩時間は概ね一致。賃料と用途条件には差異あり。",
    "checkedAt": "2026-09-23",
    "listingState": "unverified",
    "listingNote": "原掲載を取得できず、賃料・用途の相違も未解消。"
  },
  {
    "id": "tsuchiya-2f",
    "name": "土屋ビル 2階",
    "station": "新大久保",
    "walk": 3,
    "address": "東京都新宿区百人町2-5-4",
    "type": "貸事務所（officee表記）",
    "area": 195.04,
    "floor": "2階 / 8階建",
    "rent": "91万円 / 月（税別・共益費込）",
    "structure": "SRC・1989年・新耐震",
    "elevator": "有（1基）",
    "exits": "不明",
    "published": "媒体最終確認 2026-09-03",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "ワンフロアで面積は十分。2階のため、2方向避難・階段幅・防火区画・EVを図面確認。用途変更の可能性も行政へ要相談。",
    "source": "https://officee.jp/detail/14385/476066",
    "sourceName": "officee",
    "evidence": "59坪。㎡数は前回記録（換算・丸め差あり）。別媒体の86万円＋共益費5万円（税別）と合計一致。大久保徒歩7分、入居予定2026年11月。",
    "checkedAt": "2026-09-23",
    "listingState": "pending",
    "listingNote": "officeeに「内定」と表示。通常の空室とみなさず受付可否を確認。",
    "access": [
      {
        "station": "新大久保",
        "walk": 3
      },
      {
        "station": "大久保",
        "walk": 7
      }
    ],
    "contact": {
      "building": "土屋ビル",
      "url": "https://officee.jp/detail/14385/476066",
      "company": "47株式会社 / officee",
      "contact": "0120-981-247（平日9:00〜19:00）"
    }
  },
  {
    "id": "tsuchiya-3f",
    "name": "土屋ビル 3階",
    "station": "新大久保",
    "walk": 3,
    "address": "東京都新宿区百人町2-5-4",
    "type": "貸事務所（officee表記）",
    "area": 195.05,
    "floor": "3階 / 8階建",
    "rent": "91万円 / 月（税別・共益費込）",
    "structure": "SRC・1989年・新耐震",
    "elevator": "有（1基）",
    "exits": "不明",
    "published": "媒体最終確認 2026-09-03",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "面積は十分だが3階は幼児避難のハードルが上がる。屋外階段を含む2方向避難、排煙、消防設備、EVを最優先で確認。",
    "source": "https://officee.jp/detail/14385/62348",
    "sourceName": "officee",
    "evidence": "59坪。㎡数は前回記録（換算・丸め差あり）。別媒体の86万円＋共益費5万円（税別）と合計一致。大久保徒歩7分、入居予定2026年11月。",
    "checkedAt": "2026-09-23",
    "listingState": "pending",
    "listingNote": "officeeに「内定」と表示。通常の空室とみなさず受付可否を確認。",
    "access": [
      {
        "station": "新大久保",
        "walk": 3
      },
      {
        "station": "大久保",
        "walk": 7
      }
    ],
    "contact": {
      "building": "土屋ビル",
      "url": "https://officee.jp/detail/14385/62348",
      "company": "47株式会社 / officee",
      "contact": "0120-981-247（平日9:00〜19:00）"
    }
  },
  {
    "id": "kabukicho-2f",
    "name": "歌舞伎町2丁目・店舗（2階）",
    "station": "新宿",
    "walk": 3,
    "address": "東京都新宿区歌舞伎町2丁目",
    "type": "貸店舗・居抜き",
    "area": 99.17,
    "floor": "2階",
    "rent": "相談",
    "structure": "不明",
    "elevator": "不明",
    "exits": "不明",
    "published": "掲載日・媒体更新日：不明",
    "fit": "review",
    "fitLabel": "条件照合が必要",
    "reason": "募集継続・物件同一性が未確認のため適性は判定保留。旧記録の2階・99.17㎡等を採用前に照合し、保育用途と避難条件を確認。",
    "source": "https://bk-sagasa-nt.com/tokyo/properties/8247/",
    "sourceName": "ぶけなび（旧記録の参照先）",
    "evidence": "旧記録の新宿3分・新大久保5分、ビル名等は未再検証。別物件の可能性もあるため断定しません。",
    "checkedAt": "2026-09-23",
    "listingState": "unverified",
    "listingNote": "原掲載を取得できず、旧記録との物件同一性・駅徒歩・ビル名を再確認できません。",
    "contact": {
      "building": "ビル名：不明（旧記録との同一性未確認）",
      "url": "https://bk-sagasa-nt.com/tokyo/properties/8247/",
      "company": "現在の取扱会社：不明",
      "contact": "旧参照先の物件ID 8247。まず物件の同一性と募集状況を確認。"
    }
  },
  {
    "id": "tk-shintoshin-2f",
    "name": "TK新都心ビル 2階",
    "station": "新宿",
    "walk": 5,
    "address": "東京都新宿区西新宿1-23-1",
    "type": "事務所",
    "area": 158.04,
    "floor": "2階 / 地上10階・地下2階",
    "rent": "141.9957万円 / 月（税込・共益費込）",
    "structure": "SRC・RC・1992年11月・新耐震",
    "elevator": "有（1基）",
    "exits": "不明",
    "published": "媒体更新 2025-10-09（取得できたページ）",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "駅近・新耐震・EVありで建物条件は良い。一方、事務所募集のため保育用途への変更可否と2方向避難、給排水工事可否を先に確認。",
    "source": "https://www.officetar.jp/building/2220/150730/",
    "sourceName": "オフィスター",
    "evidence": "158.04㎡。徒歩は駅表の新宿5分を採用（説明文は3分で相違）。現行賃料と空室は仲介会社へ要確認。",
    "checkedAt": "2026-09-23",
    "listingState": "unverified",
    "listingNote": "取得ページの更新日が古いため、現在の空室・賃料は要再確認。",
    "access": [
      {
        "station": "新宿",
        "walk": 5
      },
      {
        "station": "西新宿",
        "walk": 8
      }
    ]
  },
  {
    "id": "minami-ikebukuro-1f",
    "name": "南池袋2丁目・店舗事務所（1階）",
    "station": "池袋",
    "walk": 6,
    "address": "東京都豊島区南池袋2丁目",
    "type": "店舗 / 事務所・スケルトン",
    "area": 133.46,
    "floor": "1階 / 地上10階・地下1階",
    "rent": "186.5094万円 / 月",
    "structure": "S造・2014年12月",
    "elevator": "有（2基以上）",
    "exits": "不明",
    "published": "公開 2026-07-23／次回更新予定 2026-08-20（期限経過）",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "1階・133.46㎡の店舗事務所。最新募集状況と保育用途、送迎スペース、独立2出口、採光、賃料を含む事業性を重点確認。",
    "source": "https://mapfan.com/realestate/details/69ba21ba020c0805a5fa1eea",
    "sourceName": "MapFan / アットホーム",
    "evidence": "池袋6分／東池袋5分に訂正。現況使用中・引渡予定8月初旬の古い表記が残るため空室未確認。ビル名は本原掲載に記載なし。",
    "checkedAt": "2026-09-23",
    "listingState": "unverified",
    "listingNote": "次回更新予定日が経過。募集継続と入居時期を再確認してください。",
    "contact": {
      "building": "ビル名：不明",
      "url": "https://mapfan.com/realestate/details/69ba21ba020c0805a5fa1eea",
      "company": "株式会社バイオンマネジメント",
      "contact": "03-5985-4521／物件番号 6989968754"
    }
  },
  {
    "id": "ikebukuro-first",
    "name": "池袋ファーストビル 3階",
    "station": "池袋",
    "walk": 3,
    "address": "東京都豊島区西池袋3-29-11",
    "type": "店舗 / 事務所",
    "area": 126.02,
    "floor": "3階 / 地上6階・地下1階",
    "rent": "82.5万円 / 月（税込）",
    "structure": "RC・1980年11月",
    "elevator": "不明（旧記録に1基、今回の原掲載では未再確認）",
    "exits": "不明",
    "published": "媒体更新 2026-08-05",
    "fit": "review",
    "fitLabel": "要重点確認",
    "reason": "3階・126.02㎡。1980年竣工のため耐震資料と避難計画を重点確認。独立2出口・保育用途承諾は不明。EVの旧記録は現地・図面で再確認。",
    "source": "https://tempoly.jp/property/O-1031432911-3",
    "sourceName": "TEMPOLY",
    "evidence": "126.02㎡・82.5万円税込・3階の募集詳細を確認。管理費は不明（媒体は「－」）。看板料2万円税別の記載。",
    "checkedAt": "2026-09-23",
    "listingState": "listed",
    "listingNote": "公開ページに空家・即時の表示あり。媒体更新は8月のため問い合わせ時に再確認。"
  },
  {
    "id": "homes-takadanobaba-2f",
    "name": "高田馬場・貸事務所（2階）",
    "station": "高田馬場",
    "walk": 4,
    "address": "東京都新宿区高田馬場",
    "type": "貸事務所",
    "area": 63.14,
    "floor": "2階",
    "rent": "27.5万円 / 月",
    "structure": "S造・1993年10月",
    "elevator": "不明（掲載終了のため再確認不可）",
    "exits": "不明",
    "published": "掲載日・媒体更新日：不明（掲載終了）",
    "fit": "inactive",
    "fitLabel": "過去情報",
    "reason": "募集・掲載終了の記録です。現在の検討候補からは除外し、対応履歴を残しています。掲載終了だけでは成約の有無は判断できません。",
    "source": "https://www.homes.co.jp/chintai/b-1457150042363/",
    "sourceName": "LIFULL HOME'S",
    "evidence": "HOME'S物件番号 0145715-0042363。63.14㎡、2階、鉄骨造、エレベーターありとして掲載。 条件・設備は2026-09-21の旧記録です。",
    "checkedAt": "2026-09-22",
    "listingState": "ended",
    "listingNote": "HOME'S原掲載に掲載終了の表示。成約済みとは断定しません。",
    "contact": {
      "building": "ビル名：不明",
      "url": "https://www.homes.co.jp/chintai/b-1457150042363/",
      "company": "現在の取扱窓口：不明",
      "contact": "掲載終了ページ。旧問い合わせ番号の有効性は未確認のため、現行の連絡先としては案内しません。"
    }
  },
  {
    "id": "homes-takadanobaba-1f",
    "name": "高田馬場1丁目・貸事務所（1階）",
    "station": "高田馬場",
    "walk": 6,
    "address": "東京都新宿区高田馬場1丁目",
    "type": "貸事務所",
    "area": 66.11,
    "floor": "1階",
    "rent": "28.6万円 / 月",
    "structure": "SRC・築44年",
    "elevator": "不明（掲載終了のため再確認不可）",
    "exits": "不明",
    "published": "掲載日・媒体更新日：不明（掲載終了）",
    "fit": "inactive",
    "fitLabel": "過去情報",
    "reason": "募集・掲載終了の記録です。現在の検討候補からは除外し、対応履歴を残しています。掲載終了だけでは成約の有無は判断できません。",
    "source": "https://www.homes.co.jp/chintai/b-1457150043147/",
    "sourceName": "LIFULL HOME'S",
    "evidence": "at home 6984123095は1階66.12㎡・28.6万円・高田馬場6分・SRC1982年10月。2026-09-22に掲載確認。同一区画か不明。プラスファイブ・コンストラクション 03-6755-5721（9〜20時）へ同一性を確認可能。",
    "checkedAt": "2026-09-22",
    "listingState": "ended",
    "listingNote": "HOME'Sは掲載終了。at homeに類似募集あり（同一性未確認、重複計上しない）。",
    "contact": {
      "building": "ビル名：不明",
      "url": "https://www.homes.co.jp/chintai/b-1457150043147/",
      "company": "現在の取扱窓口：不明",
      "contact": "掲載終了ページ。旧問い合わせ番号の有効性は未確認のため、現行の連絡先としては案内しません。"
    },
    "relatedSource": {
      "url": "https://www.athome.co.jp/rent_store/6984123095/",
      "label": "at homeの類似区画（同一性未確認）"
    }
  },
  {
    "id": "homes-carmel-103",
    "name": "カーメルI 103",
    "station": "西新宿",
    "walk": 4,
    "address": "東京都新宿区西新宿",
    "type": "貸店舗 / 事務所",
    "area": 65.59,
    "floor": "1階 / 8階建",
    "rent": "34.9184万円 / 月",
    "structure": "築37年（構造は要確認）",
    "elevator": "不明（掲載終了のため再確認不可）",
    "exits": "不明",
    "published": "掲載日・媒体更新日：不明（掲載終了）",
    "fit": "inactive",
    "fitLabel": "過去情報",
    "reason": "募集・掲載終了の記録です。現在の検討候補からは除外し、対応履歴を残しています。掲載終了だけでは成約の有無は判断できません。",
    "source": "https://www.homes.co.jp/chintai/b-1577540000026/",
    "sourceName": "LIFULL HOME'S",
    "evidence": "西新宿駅徒歩4分、新宿駅徒歩13分。1階103号室、65.59㎡として掲載。 条件・設備は2026-09-21の旧記録です。",
    "checkedAt": "2026-09-22",
    "listingState": "ended",
    "listingNote": "HOME'S原掲載に掲載終了の表示。成約済みとは断定しません。",
    "contact": {
      "building": "カーメルI",
      "url": "https://www.homes.co.jp/chintai/b-1577540000026/",
      "company": "現在の取扱窓口：不明",
      "contact": "掲載終了ページ。旧問い合わせ番号の有効性は未確認のため、現行の連絡先としては案内しません。"
    }
  },
  {
    "fit": "review",
    "fitLabel": "要重点確認",
    "elevator": "不明",
    "exits": "不明",
    "listingState": "listed",
    "listingNote": "原掲載を確認。現在の空室・保育用途の承諾は仲介会社への確認が必要。",
    "checkedAt": "2026-09-23",
    "sourceName": "at home（直接確認）",
    "id": "athome-wakatsuki-201",
    "name": "若月ビル 201",
    "station": "高田馬場",
    "walk": 5,
    "address": "東京都新宿区高田馬場1丁目（番地不明）",
    "type": "貸店舗・事務所",
    "area": 61.62,
    "floor": "2階 / 4階建",
    "rent": "29.7万円＋管理費0.55万円 / 月（税区分不明）",
    "structure": "RC・1973年12月",
    "published": "公開 2026-08-04／更新日不明／次回更新予定 2026-09-29",
    "reason": "2階・61.62㎡。保育に使える実効面積、2方向避難、EV、耐震資料を確認。定期借家3年のため長期運営の継続性にも注意。",
    "evidence": "東西線高田馬場5分。空・引渡相談。塾等の業種相談表示は保育用途の承諾ではありません。",
    "source": "https://www.athome.co.jp/rent_store/6991736061/",
    "contact": {
      "building": "若月ビル",
      "url": "https://www.athome.co.jp/rent_store/6991736061/",
      "company": "株式会社アースウィンド 麹町店",
      "contact": "03-3354-5666（平日9:00〜18:00）／物件番号6991736061"
    }
  },
  {
    "fit": "review",
    "fitLabel": "要重点確認",
    "elevator": "不明",
    "exits": "不明",
    "listingState": "listed",
    "listingNote": "原掲載を確認。現在の空室・保育用途の承諾は仲介会社への確認が必要。",
    "checkedAt": "2026-09-23",
    "sourceName": "at home（直接確認）",
    "id": "athome-ars-waseda-2f",
    "name": "東急ドエル・アルス早稲田 2階",
    "station": "早稲田",
    "walk": 8,
    "access": [
      {
        "station": "早稲田",
        "walk": 8
      },
      {
        "station": "高田馬場",
        "walk": 13
      }
    ],
    "address": "東京都新宿区西早稲田2丁目（番地不明）",
    "type": "貸店舗・事務所",
    "area": 85.39,
    "floor": "2階 / 9階建",
    "rent": "36.96万円 / 月（管理費・税区分不明）",
    "structure": "SRC・1990年2月",
    "published": "公開 2026-07-23／更新日不明／次回更新予定 2026-09-28",
    "reason": "2階・85.39㎡。保育用途、独立した2出口、階段・EV、採光・換気、児童用設備工事の可否を確認。スクール相談可だけでは保育施設可と判断できません。",
    "evidence": "東西線早稲田8分・JR高田馬場13分。空・即時引渡、契約2年。",
    "source": "https://www.athome.co.jp/rent_store/6991218695/",
    "contact": {
      "building": "東急ドエル・アルス早稲田",
      "url": "https://www.athome.co.jp/rent_store/6991218695/",
      "company": "有限会社高田馬場不動産",
      "contact": "03-3208-3861（10:00〜19:00、日曜・祭日休）／物件番号6991218695"
    }
  },
  {
    "fit": "review",
    "fitLabel": "要重点確認",
    "elevator": "不明",
    "exits": "不明",
    "listingState": "listed",
    "listingNote": "原掲載を確認。現在の空室・保育用途の承諾は仲介会社への確認が必要。",
    "checkedAt": "2026-09-23",
    "sourceName": "at home（直接確認）",
    "id": "athome-house-nijiiro-2f",
    "name": "House虹色 2階",
    "station": "高田馬場",
    "walk": 8,
    "address": "東京都新宿区高田馬場1丁目（番地不明）",
    "type": "貸店舗・クリニック居抜き",
    "area": 63.01,
    "floor": "2階 / 4階建",
    "rent": "38.5万円 / 月（管理費・税区分不明）",
    "structure": "RC・2012年8月",
    "published": "公開 2026-09-19／更新日不明／次回更新予定 2026-10-03",
    "reason": "2階・63.01㎡で、設備を除く実効保育面積の検討が必要。2方向避難、EV、保育用途、クリニック内装の転用可否を確認。",
    "evidence": "JR高田馬場8分／東西線7分。使用中・引渡相談、定期借家5年。他業種相談の表示あり。",
    "source": "https://www.athome.co.jp/rent_store/6992285301/",
    "contact": {
      "building": "House虹色",
      "url": "https://www.athome.co.jp/rent_store/6992285301/",
      "company": "株式会社ドリームライフウエスト",
      "contact": "047-622-5539（10:00〜18:00、不定休）／物件番号6992285301"
    }
  },
  {
    "fit": "review",
    "fitLabel": "要重点確認",
    "elevator": "不明",
    "exits": "不明",
    "listingState": "listed",
    "listingNote": "原掲載を確認。現在の空室・保育用途の承諾は仲介会社への確認が必要。",
    "checkedAt": "2026-09-23",
    "sourceName": "at home（直接確認）",
    "id": "athome-takadanobaba-kodate",
    "name": "高田馬場戸建（一括）",
    "station": "高田馬場",
    "walk": 5,
    "address": "東京都新宿区高田馬場1丁目（番地不明）",
    "type": "貸店舗（建物一括）",
    "area": 80,
    "floor": "1〜2階 / 2階建（面積内訳不明）",
    "rent": "39.93万円 / 月（管理費・税区分不明）",
    "structure": "木造・1985年11月",
    "published": "公開 2026-08-04／更新日不明／次回更新予定 2026-09-26",
    "reason": "一括80㎡で各階の面積は不明。1階だけで60㎡あるとは判断できません。木造の防火・避難条件、保育用途、定期借家2年の継続性を重点確認。",
    "evidence": "媒体階数欄は1階、2階建の建物一括募集。JR高田馬場5分／東西線2分。空・引渡相談。",
    "source": "https://www.athome.co.jp/rent_store/6991735417/",
    "contact": {
      "building": "高田馬場戸建",
      "url": "https://www.athome.co.jp/rent_store/6991735417/",
      "company": "竹田馬場不動産",
      "contact": "03-5937-4086（10:00〜18:00、不定休）／物件番号6991735417"
    }
  },
  {
    "fit": "restricted",
    "fitLabel": "保育用途の取扱制限",
    "elevator": "有",
    "exits": "不明",
    "listingState": "restricted",
    "listingNote": "事務所の掲載は確認。ただし取扱会社は保育園用途の問い合わせを受け付けない旨を掲載。",
    "checkedAt": "2026-09-23",
    "sourceName": "LIFULL HOME'S（直接確認）",
    "id": "homes-flat-waseda-1f",
    "name": "フラットワセダ 1階",
    "address": "東京都新宿区西早稲田1-9-37",
    "walk": 5,
    "area": 63.28,
    "floor": "1階 / 10階建",
    "rent": "23.1万円 / 月（管理費・税区分不明）",
    "structure": "SRC・1991年11月",
    "published": "公開 2026-05-12／媒体更新 2026-09-22",
    "source": "https://www.homes.co.jp/chintai/b-1349900022914/",
    "station": "早稲田",
    "type": "貸事務所",
    "reason": "面積・駅距離・階数は検索条件内ですが、掲載窓口は保育園向け物件を扱わないと明記。この窓口への保育目的の問い合わせは推奨しません。建物自体の行政上の可否は不明。",
    "evidence": "東西線早稲田の徒歩分数を採用。EVあり。独立2出口は不明。取扱方針の確認記録として残し、有力候補には含めません。",
    "contact": {
      "building": "フラットワセダ 1階",
      "url": "https://www.homes.co.jp/chintai/b-1349900022914/",
      "company": "株式会社ライヴェックス",
      "contact": "保育用途は取扱対象外。一般事務所の窓口：0037-633-60134／問い合わせ番号918333（平日9〜18時、番号は原掲載で再確認）"
    }
  },
  {
    "fit": "restricted",
    "fitLabel": "保育用途の取扱制限",
    "elevator": "有",
    "exits": "不明",
    "listingState": "restricted",
    "listingNote": "事務所の掲載は確認。ただし取扱会社は保育園用途の問い合わせを受け付けない旨を掲載。",
    "checkedAt": "2026-09-22",
    "sourceName": "LIFULL HOME'S（直接確認）",
    "id": "homes-nobu-waseda-2f",
    "name": "NOBU西早稲田 2階",
    "address": "東京都新宿区西早稲田1-8-14",
    "walk": 9,
    "area": 60.23,
    "floor": "2階 / 5階建",
    "rent": "33万円 / 月（管理費・税区分不明）",
    "structure": "RC・2024年7月",
    "published": "公開 2025-10-29／媒体更新 2026-09-22",
    "source": "https://www.homes.co.jp/chintai/b-1349900020387/",
    "station": "早稲田",
    "type": "貸事務所",
    "reason": "面積・駅距離・階数は検索条件内ですが、掲載窓口は保育園向け物件を扱わないと明記。この窓口への保育目的の問い合わせは推奨しません。建物自体の行政上の可否は不明。",
    "evidence": "東西線早稲田の徒歩分数を採用。EVあり。独立2出口は不明。取扱方針の確認記録として残し、有力候補には含めません。",
    "contact": {
      "building": "NOBU西早稲田 2階",
      "url": "https://www.homes.co.jp/chintai/b-1349900020387/",
      "company": "株式会社ライヴェックス",
      "contact": "保育用途は取扱対象外。一般事務所の窓口：0037-633-60134／問い合わせ番号702098（平日9〜18時、番号は原掲載で再確認）"
    }
  }
];
